#ifndef HARDWARE_CFG_H_
#define HARDWARE_CFG_H_

#define LORA_SS_PIN 5
#define LORA_RESET_PIN 14
#define LORA_DIO0_PIN 36

#define SERIAL_BAUD 115000

//#define SERIAL2_BAUD 115200
#define SERIAL2_BAUD 57600

#define GROUND_ID 0
#define ROCKET_ID 1
#define FILL_STATION_ID 2

#define DEFAULT_ID GROUND_ID

#endif